### ISSUE TITLE
instantiatedGenerator.run is not a function

### ISSUE THREAD

**Issue by sergiobaiao** [Alfresco/generator-alfresco-adf-app#380]
I'm trying to run generator-alfresco-adf-app on my server, but when i can yo alfresco-adf-app it shows this:

root@i4:/files/adf# DEBUG=yeoman:generator yo alfresco-adf-app
  yeoman:generator Queueing initializing in initializing +0ms
  yeoman:generator Queueing prompting in prompting +3ms
  yeoman:generator Queueing writing in writing +0ms
  yeoman:generator Queueing install in install +0ms
  yeoman:generator Running initializing +7ms
  yeoman:generator An error occured while running initializing TypeError: instantiatedGenerator.run is not a function
    at module.exports.composeWith (/usr/lib/node_modules/generator-alfresco-adf-app/node_modules/generator-alfresco-common/node_modules/yeoman-generator/lib/index.js:585:29)
    at module.exports.initializing (/usr/lib/node_modules/generator-alfresco-adf-app/app/index.js:67:10) +1s
Error alfresco-adf-app

instantiatedGenerator.run is not a function
┌───────────────────────────────────────────────────┐
│              yo update check failed               │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

I'm running this as root, so i'm ignoring permissions errors.

node -v
v20.13.1

 npm -v
10.5.2

ls -g generator-alfresco-adf-app
/usr/lib
└── generator-alfresco-adf-app@6.1.1

 npm ls -g yo
/usr/lib
└── yo@5.0.0

**Comment by MattioliLeo** [comment]
see https://github.com/yeoman/generator-generator/issues/258
Workaround: downgrade yo to get it working, for example
`npm install -g yo@4.3.1 generator-generator`
